services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra-schema.cql:/docker-entrypoint-initdb.d/init.cql
    environment:
      CASSANDRA_START_RPC: "true"

  simulator:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    container_name: simulator
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - kafka

  stream_processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    container_name: stream_processor
    command: sh -c "echo 'Waiting 15s for Kafka...' && sleep 15 && echo 'Starting Bytewax...' && python -m bytewax.run stream_processor:flow -w 2"
    depends_on:
      - kafka

  cassandra_writer:
    build:
      context: .
      dockerfile: Dockerfile.writer
    container_name: cassandra_writer
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - kafka
      - cassandra
